version: '2.4'

volumes:
  minio-data:

services:
  app:
    image: gcavalcante8808/driftctl-exporter:${COMMIT_HASH:-dev}
    build: .
    working_dir: /usr/src
    tty: true
    environment:
      DCTL_FROM: "tfstate://./exporter/tests/fixtures/terraform.tfstate"
      RESULT_PATH: "file:///data/results.json" # rfc1808 compliant path. It will be parsed using urlparse: https://docs.python.org/3/library/urllib.parse.html.
      AWS_REGION: "us-east-1"
      AWS_ACCESS_KEY_ID:
      AWS_SECRET_ACCESS_KEY:
      AWS_SESSION_TOKEN:
    ports:
      - 8080:8080
    command:
      - sh
    volumes:
      - ./src:/usr/src
      - ./data:/data
