apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
  labels:
  {{- include "pod-with-service-ingress.labels" . | nindent 4 }}
data:
  {{- range $key, $value := .Values.environment }}
    {{ $key }}: {{ $value | quote }}
  {{ end }}
