apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: {{ .Release.Name }}
  labels:
    {{- include "pod-with-service-ingress.labels" . | nindent 4 }}
  {{- with .Values.deployment.labels }}
    {{- toYaml . | nindent 4 }}
  {{- end }}
  annotations:
    checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
    checksum/secrets: {{ include (print $.Template.BasePath "/secret.yaml") . | sha256sum }}
    checksum/driftignore: {{ include (print $.Template.BasePath "/driftignore.yaml") . | sha256sum }}
spec:
  jobTemplate:
    metadata:
      name: {{ .Release.Name }}
    spec:
      template:
        metadata:
          annotations:
            checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
            checksum/secrets: {{ include (print $.Template.BasePath "/secret.yaml") . | sha256sum }}
            checksum/driftignore: {{ include (print $.Template.BasePath "/driftignore.yaml") . | sha256sum }}
        spec:
          serviceAccountName: {{ .Values.serviceAccount.name | default .Release.Name }}
          containers:
            - name: {{ .Release.Name }}-initial-scan
              image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
              imagePullPolicy: {{ default "IfNotPresent" .Values.image.pullPolicy }}
              env:
              {{- with .Values.extraEnv }}
                {{- toYaml . | nindent 10 }}
              {{- end }}
              envFrom:
                - configMapRef:
                    name: {{ .Release.Name }}
                - secretRef:
                    name: {{ .Release.Name }}
                {{- with .Values.extraEnvFrom }}
                {{- toYaml . | nindent 12 }}
                {{- end }}
              command:
                - python
                - scan.py
              volumeMounts:
                - name: driftignore
                  mountPath: /usr/src/.driftignore
                  subPath: .driftignore
                  readOnly: true
          volumes:
            - name: driftignore
              configMap:
                name: {{ .Release.Name }}-driftignore
          restartPolicy: OnFailure
  schedule: {{ .Values.cronjob.schedule }}
status: {}
