test:
	pytest .

coverage:
  pytest --cov-report term \
        --cov-report xml:coverage.xml \
        --cov-report html \
        --cov=.

flake8:
    flake8 .

bandit:
    bandit -r -c .bandit.yml .
