name: PublishDockerImage
on:
  push:
    branches:
      - main

jobs:
  build-n-push:
    runs-on: ubuntu-latest
    env:
      COMPOSE_DOCKER_CLI_BUILD: 1
      DOCKER_BUILDKIT: 1
    steps:
      - uses: actions/checkout@v2
      - uses: extractions/setup-just@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: build-docker-image
        run: |
          just --set image_tag ${GITHUB_SHA} build-docker-image
          just --set image_tag latest build-docker-image

      - name: publish-docker-image
        run: |
          just --set image_tag ${GITHUB_SHA} publish-docker-image
          just --set image_tag latest publish-docker-image
