name: PublishDockerImage
on:
  push:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      COMPOSE_DOCKER_CLI_BUILD: 1
      DOCKER_BUILDKIT: 1
      COMMIT_HASH: ${{ env.GITHUB_SHA }}
    steps:
      - uses: actions/checkout@v2

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: build-image-with-hash
        run: docker-compose build app

      - name: build-image-as-latest
        run: COMMIT_HASH=latest docker-compose build
