name: build-n-test
on:
  workflow_call:
  pull_request:

jobs:
  unittests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Test Coverage
        run: docker-compose -f docker-compose.yaml -f docker-compose.tests.yaml up --exit-code-from app

      - name: CodeCov Upload
        uses: codecov/codecov-action@v1
        with:
          files: src/coverage.xml

  chart-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Run helm chart unittests
        run: just helm-chart-tests