name: build-n-test
on:
  workflow_call:
  pull_request:

jobs:
  unittests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: extractions/setup-just@v1

      - name: Code Coverage
        run: just python-tests

      - name: CodeCov Upload
        uses: codecov/codecov-action@v1
        with:
          files: src/coverage.xml

  chart-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: extractions/setup-just@v1

      - name: Run helm chart unittests
        run: just helm-chart-tests
