name: TrivyScan
on:
  workflow_call:
  push:
    branches:
      - main
  pull_request:

jobs:
  vulnerability-scan:
    runs-on: ubuntu-latest
    env:
      COMPOSE_DOCKER_CLI_BUILD: 1
      DOCKER_BUILDKIT: 1
    steps:
      - uses: actions/checkout@v2
      - uses: extractions/setup-just@v1

      - name: build-docker-image
        run: |
          just --set image_tag ${GITHUB_SHA} build-docker-image
          just --set image_tag latest build-docker-image

      - name: Run Trivy vulnerability scanner in report mode
        run: just --set image_tag ${GITHUB_SHA} --set trivy_exit_code 0 scan-docker-image

      # We can't run trivy action on a local image yet. https://github.com/aquasecurity/trivy-action/issues/68
      # So we going to install it and use it directly.
      - name: Run Trivy vulnerability scanner in report mode
        run: just --set image_tag ${GITHUB_SHA} --set trivy_format "sarif" --set trivy_output "report.sarif" scan-docker-image

      - name: Upload Trivy scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v1
        with:
          sarif_file: 'report.sarif'
